import { useState } from "react";
import { loading } from "../assets";
import { handleImageGeneration } from "../utils/generate"; // Make sure this path is correct

const Generating = ({ className }) => {
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [imageResult, setImageResult] = useState(null);

  const handleGenerate = async (e) => {
    // Trigger on Enter key or button click
    if (e.key === "Enter" || e.type === "click") {
      if (!prompt || isGenerating) return;

      setIsGenerating(true);
      try {
        const url = await handleImageGeneration(prompt);
        setImageResult(url);
      } catch (error) {
        console.error("Failed to generate image:", error);
      } finally {
        setIsGenerating(false);
      }
    }
  };

  return (
    <div className={`${className || ""} flex flex-col items-center w-full`}>
      {/* Input Bar */}
      <div className="flex items-center h-[3.5rem] px-6 bg-n-8/80 rounded-[1.7rem] text-base w-full border border-n-1/10 backdrop-blur">
        <img
          src={loading}
          alt="Loading"
          className={`w-5 h-5 mr-4 ${isGenerating ? "animate-spin" : ""}`}
        />
        <input
          type="text"
          className="bg-transparent border-none outline-none text-white w-full body-2 placeholder:text-n-4"
          placeholder="Describe what you want to generate..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={handleGenerate}
        />
        <button 
          onClick={handleGenerate}
          disabled={isGenerating}
          className="ml-4 text-n-1 font-code font-bold hover:text-purple-400 transition-colors uppercase tracking-wider text-xs"
        >
          {isGenerating ? "Wait" : "Gen"}
        </button>
      </div>

      {/* Result Display - This will pop up below the bar when ready */}
      {imageResult && (
        <div className="mt-6 p-2 bg-n-7 rounded-2xl border border-n-6 shadow-2xl transition-all animate-in fade-in zoom-in">
          <img 
            src={imageResult} 
            alt="AI Result" 
            className="rounded-xl w-full max-w-[350px] md:max-w-[450px]" 
          />
          <div className="flex justify-between items-center p-2">
             <span className="text-xs text-n-4">Generated by Brainwave</span>
             <a 
               href={imageResult} 
               download="ai-image.png" 
               className="text-xs text-purple-400 hover:underline"
               target="_blank" 
               rel="noreferrer"
             >
               Save Image
             </a>
          </div>
        </div>
      )}
    </div>
  );
};

export default Generating;
